package org.ReducerSide;

public enum ReducerPreparationType {
    REDUCER_PREPARE_FILTER,
    REDUCER_PREPARE_SHOP_CATEGORY_SALES,
    REDUCER_PREPARE_PRODUCT_CATEGORY_SALES,
    REDUCER_ADD_WORKER_CONNECTION,
    REDUCER_END_OF_WORKERS,
}
