package org.Workers;

public enum WorkerCommandType {
    QUIT,
    ADD_BACKUP,
    END_BACKUP_LIST,
    ADD_SHOP,
    SYNC_ADD_SHOP,
    CHOSE_SHOP,
    ADD_PRODUCT_TO_SHOP,
    SYNC_ADD_PRODUCT_TO_SHOP,
    REMOVE_PRODUCT_FROM_SHOP,
    SYNC_REMOVE_PRODUCT_FROM_SHOP,
    ADD_PRODUCT_STOCK,
    SYNC_ADD_PRODUCT_STOCK,
    REMOVE_PRODUCT_STOCK,
    SYNC_REMOVE_PRODUCT_STOCK,
    GET_SHOP_CATEGORY_SALES,
    GET_PRODUCT_CATEGORY_SALES,
    REDUCER_ACK_OK,
    GET_CART,
    ADD_TO_CART,
    CHECKOUT_CART,
    SYNC_CHECKOUT_CART,
    FILTER
}
